vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        posts:
           uri_prefix: /images/posts
           upload_destination: '%kernel.project_dir%/public/images/posts'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
